// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosissamples.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the DocmosisSamples module
	public static void act_Invoice_RenderPDF(IContext context, docmosissamples.proxies.Invoice _invoice)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Invoice", _invoice == null ? null : _invoice.getMendixObject());
		Core.microflowCall("DocmosisSamples.Act_Invoice_RenderPDF").withParams(params).execute(context);
	}
	public static boolean bCo_InvoiceLine(IContext context, docmosissamples.proxies.InvoiceLine _invoiceLine)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("InvoiceLine", _invoiceLine == null ? null : _invoiceLine.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("DocmosisSamples.BCo_InvoiceLine").withParams(params).execute(context);
	}
}