// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloudimplementation.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DocmosisCloudImplementation module
	public static void act_RenderDevMode_Generate(IContext context, docmosiscloudimplementation.proxies.RenderDevMode _renderDevMode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RenderDevMode", _renderDevMode == null ? null : _renderDevMode.getMendixObject());
		Core.microflowCall("DocmosisCloudImplementation.Act_RenderDevMode_Generate").withParams(params).execute(context);
	}
	public static void act_TemplateJSONStructure_Generate(IContext context, docmosiscloudimplementation.proxies.TemplateJSONStructure _templateJSONStructure)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateJSONStructure", _templateJSONStructure == null ? null : _templateJSONStructure.getMendixObject());
		Core.microflowCall("DocmosisCloudImplementation.Act_TemplateJSONStructure_Generate").withParams(params).execute(context);
	}
	public static docmosiscloudimplementation.proxies.API aPI_GetForCurrentSession(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.API_GetForCurrentSession").withParams(params).execute(context);
		return result == null ? null : docmosiscloudimplementation.proxies.API.initialize(context, result);
	}
	public static docmosiscloudimplementation.proxies.API dS_API(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.DS_API").withParams(params).execute(context);
		return result == null ? null : docmosiscloudimplementation.proxies.API.initialize(context, result);
	}
	public static docmosiscloudimplementation.proxies.RenderDevMode dS_RenderDevMode_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.DS_RenderDevMode_Create").withParams(params).execute(context);
		return result == null ? null : docmosiscloudimplementation.proxies.RenderDevMode.initialize(context, result);
	}
	public static docmosiscloudimplementation.proxies.TemplateJSONStructure dS_TemplateJSONStructure_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.DS_TemplateJSONStructure_Create").withParams(params).execute(context);
		return result == null ? null : docmosiscloudimplementation.proxies.TemplateJSONStructure.initialize(context, result);
	}
	public static docmosiscloud.proxies.RenderResponse renderDevMode_Generate(IContext context, java.lang.String _templateName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateName", _templateName);
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.RenderDevMode_Generate").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.RenderResponse.initialize(context, result);
	}
	public static java.lang.String response_FormatMessage(IContext context, docmosiscloud.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		return (java.lang.String) Core.microflowCall("DocmosisCloudImplementation.Response_FormatMessage").withParams(params).execute(context);
	}
	public static void response_HandleError(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_HandleError").withParams(params).execute(context);
	}
	public static void response_HandleException(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_HandleException").withParams(params).execute(context);
	}
	public static void response_ProcessError(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_ProcessError").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.GetSampleDataResponse templateJSONStructure_Generate(IContext context, java.lang.String _templateName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateName", _templateName);
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.TemplateJSONStructure_Generate").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.GetSampleDataResponse.initialize(context, result);
	}
}