// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloudimplementation.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DocmosisCloudImplementation module
	public static void act_TemplateStructure_Generate(IContext context, docmosiscloudimplementation.proxies.TemplateStructure _templateStructure)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateStructure", _templateStructure == null ? null : _templateStructure.getMendixObject());
		Core.microflowCall("DocmosisCloudImplementation.Act_TemplateStructure_Generate").withParams(params).execute(context);
	}
	public static docmosiscloudimplementation.proxies.TemplateStructure dS_TemplateStructure_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.DS_TemplateStructure_Create").withParams(params).execute(context);
		return result == null ? null : docmosiscloudimplementation.proxies.TemplateStructure.initialize(context, result);
	}
	public static java.lang.String invoice_CreateInvoiceData(IContext context, docmosissamples.proxies.Invoice _invoice)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Invoice", _invoice == null ? null : _invoice.getMendixObject());
		return (java.lang.String) Core.microflowCall("DocmosisCloudImplementation.Invoice_CreateInvoiceData").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.RenderResponse invoice_CreatePDF(IContext context, docmosissamples.proxies.Invoice _invoice)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Invoice", _invoice == null ? null : _invoice.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.Invoice_CreatePDF").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.RenderResponse.initialize(context, result);
	}
	public static java.lang.String response_FormatMessage(IContext context, docmosiscloud.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		return (java.lang.String) Core.microflowCall("DocmosisCloudImplementation.Response_FormatMessage").withParams(params).execute(context);
	}
	public static void response_HandleError(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_HandleError").withParams(params).execute(context);
	}
	public static void response_HandleException(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_HandleException").withParams(params).execute(context);
	}
	public static void response_ProcessError(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloudImplementation.Response_ProcessError").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.GetSampleDataResponse templateStructure_Generate(IContext context, java.lang.String _templateName)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateName", _templateName);
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloudImplementation.TemplateStructure_Generate").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.GetSampleDataResponse.initialize(context, result);
	}
}