// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloudunittesting.proxies;

public class EmployeeRender extends docmosiscloud.proxies.RenderRequest
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocmosisCloudUnitTesting.EmployeeRender";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TemplateName("TemplateName"),
		OutputName("OutputName"),
		OutputFormat("OutputFormat"),
		StoreTo("StoreTo"),
		CompressSingleFormat("CompressSingleFormat"),
		DevMode("DevMode"),
		data("data"),
		MailSubject("MailSubject"),
		MailBodyHtml("MailBodyHtml"),
		MailBodyText("MailBodyText"),
		MailNoZipAttachments("MailNoZipAttachments"),
		MailGatewayName("MailGatewayName"),
		SourceId("SourceId"),
		StylesInText("StylesInText"),
		PasswordProtect("PasswordProtect"),
		PdfWatermark("PdfWatermark"),
		PdfWatermarkColor("PdfWatermarkColor"),
		PdfWatermarkFontSize("PdfWatermarkFontSize"),
		PdfWatermarkFontName("PdfWatermarkFontName"),
		PdfWatermarkRotation("PdfWatermarkRotation"),
		PdfArchiveMode("PdfArchiveMode"),
		PdfVersion("PdfVersion"),
		PdfUniversalAccessibility("PdfUniversalAccessibility"),
		PdfTagged("PdfTagged"),
		PdfSkipEmptyPages("PdfSkipEmptyPages"),
		PdfRestrictPassword("PdfRestrictPassword"),
		PdfRestrictPrinting("PdfRestrictPrinting"),
		PdfRestrictEditing("PdfRestrictEditing"),
		PdfRestrictCopy("PdfRestrictCopy"),
		PdfRestrictAllowAccessibilty("PdfRestrictAllowAccessibilty"),
		StrictParams("StrictParams"),
		Tags("Tags"),
		StreamResultInResponse("StreamResultInResponse"),
		APIAccessKey("APIAccessKey"),
		APIEndPoint("APIEndPoint"),
		RequestID("RequestID"),
		EmployeeRender_EmployeeRenderData("DocmosisCloudUnitTesting.EmployeeRender_EmployeeRenderData");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmployeeRender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmployeeRender(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeRenderMendixObject)
	{
		super(context, employeeRenderMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, employeeRenderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'EmployeeRender.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmosiscloudunittesting.proxies.EmployeeRender initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmosiscloudunittesting.proxies.EmployeeRender.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static docmosiscloudunittesting.proxies.EmployeeRender initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new docmosiscloudunittesting.proxies.EmployeeRender(context, mendixObject);
	}

	public static docmosiscloudunittesting.proxies.EmployeeRender load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmosiscloudunittesting.proxies.EmployeeRender.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmployeeRender_EmployeeRenderData
	 */
	public final docmosiscloudunittesting.proxies.EmployeeRenderData getEmployeeRender_EmployeeRenderData() throws com.mendix.core.CoreException
	{
		return getEmployeeRender_EmployeeRenderData(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeRender_EmployeeRenderData
	 * @throws com.mendix.core.CoreException
	 */
	public final docmosiscloudunittesting.proxies.EmployeeRenderData getEmployeeRender_EmployeeRenderData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		docmosiscloudunittesting.proxies.EmployeeRenderData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeRender_EmployeeRenderData.toString());
		if (identifier != null) {
			result = docmosiscloudunittesting.proxies.EmployeeRenderData.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmployeeRender_EmployeeRenderData
	 * @param employeerender_employeerenderdata
	 */
	public final void setEmployeeRender_EmployeeRenderData(docmosiscloudunittesting.proxies.EmployeeRenderData employeerender_employeerenderdata)
	{
		setEmployeeRender_EmployeeRenderData(getContext(), employeerender_employeerenderdata);
	}

	/**
	 * Set value of EmployeeRender_EmployeeRenderData
	 * @param context
	 * @param employeerender_employeerenderdata
	 */
	public final void setEmployeeRender_EmployeeRenderData(com.mendix.systemwideinterfaces.core.IContext context, docmosiscloudunittesting.proxies.EmployeeRenderData employeerender_employeerenderdata)
	{
		if (employeerender_employeerenderdata == null) {
			getMendixObject().setValue(context, MemberNames.EmployeeRender_EmployeeRenderData.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmployeeRender_EmployeeRenderData.toString(), employeerender_employeerenderdata.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmosiscloudunittesting.proxies.EmployeeRender that = (docmosiscloudunittesting.proxies.EmployeeRender) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
