// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloudunittesting.proxies;

public class Employee
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocmosisCloudUnitTesting.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmployeeID("EmployeeID"),
		FullName("FullName"),
		StartedOn("StartedOn"),
		Employee_EmployeeRenderData("DocmosisCloudUnitTesting.Employee_EmployeeRenderData");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DocmosisCloudUnitTesting.Employee"));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DocmosisCloudUnitTesting.Employee", employeeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DocmosisCloudUnitTesting.Employee");

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmosiscloudunittesting.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmosiscloudunittesting.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static docmosiscloudunittesting.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new docmosiscloudunittesting.proxies.Employee(context, mendixObject);
	}

	public static docmosiscloudunittesting.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmosiscloudunittesting.proxies.Employee.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of EmployeeID
	 */
	public final java.lang.Long getEmployeeID()
	{
		return getEmployeeID(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeID
	 */
	public final java.lang.Long getEmployeeID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.EmployeeID.toString());
	}

	/**
	 * Set value of EmployeeID
	 * @param employeeid
	 */
	public final void setEmployeeID(java.lang.Long employeeid)
	{
		setEmployeeID(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeID
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeID.toString(), employeeid);
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn()
	{
		return getStartedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartedOn.toString());
	}

	/**
	 * Set value of StartedOn
	 * @param startedon
	 */
	public final void setStartedOn(java.util.Date startedon)
	{
		setStartedOn(getContext(), startedon);
	}

	/**
	 * Set value of StartedOn
	 * @param context
	 * @param startedon
	 */
	public final void setStartedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startedon)
	{
		getMendixObject().setValue(context, MemberNames.StartedOn.toString(), startedon);
	}

	/**
	 * @return value of Employee_EmployeeRenderData
	 */
	public final docmosiscloudunittesting.proxies.EmployeeRenderData getEmployee_EmployeeRenderData() throws com.mendix.core.CoreException
	{
		return getEmployee_EmployeeRenderData(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_EmployeeRenderData
	 */
	public final docmosiscloudunittesting.proxies.EmployeeRenderData getEmployee_EmployeeRenderData(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		docmosiscloudunittesting.proxies.EmployeeRenderData result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_EmployeeRenderData.toString());
		if (identifier != null)
			result = docmosiscloudunittesting.proxies.EmployeeRenderData.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Employee_EmployeeRenderData
	 * @param employee_employeerenderdata
	 */
	public final void setEmployee_EmployeeRenderData(docmosiscloudunittesting.proxies.EmployeeRenderData employee_employeerenderdata)
	{
		setEmployee_EmployeeRenderData(getContext(), employee_employeerenderdata);
	}

	/**
	 * Set value of Employee_EmployeeRenderData
	 * @param context
	 * @param employee_employeerenderdata
	 */
	public final void setEmployee_EmployeeRenderData(com.mendix.systemwideinterfaces.core.IContext context, docmosiscloudunittesting.proxies.EmployeeRenderData employee_employeerenderdata)
	{
		if (employee_employeerenderdata == null)
			getMendixObject().setValue(context, MemberNames.Employee_EmployeeRenderData.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Employee_EmployeeRenderData.toString(), employee_employeerenderdata.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmosiscloudunittesting.proxies.Employee that = (docmosiscloudunittesting.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DocmosisCloudUnitTesting.Employee";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
