// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloud.proxies;

public class DocmosisResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject docmosisResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocmosisCloud.DocmosisResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Succeeded("Succeeded"),
		ShortMessage("ShortMessage"),
		LongMessage("LongMessage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DocmosisResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DocmosisResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject docmosisResponseMendixObject)
	{
		if (docmosisResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, docmosisResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.docmosisResponseMendixObject = docmosisResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DocmosisResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmosiscloud.proxies.DocmosisResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmosiscloud.proxies.DocmosisResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static docmosiscloud.proxies.DocmosisResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new docmosiscloud.proxies.DocmosisResponse(context, mendixObject);
	}

	public static docmosiscloud.proxies.DocmosisResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmosiscloud.proxies.DocmosisResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Succeeded
	 */
	public final java.lang.Boolean getSucceeded()
	{
		return getSucceeded(getContext());
	}

	/**
	 * @param context
	 * @return value of Succeeded
	 */
	public final java.lang.Boolean getSucceeded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Succeeded.toString());
	}

	/**
	 * Set value of Succeeded
	 * @param succeeded
	 */
	public final void setSucceeded(java.lang.Boolean succeeded)
	{
		setSucceeded(getContext(), succeeded);
	}

	/**
	 * Set value of Succeeded
	 * @param context
	 * @param succeeded
	 */
	public final void setSucceeded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean succeeded)
	{
		getMendixObject().setValue(context, MemberNames.Succeeded.toString(), succeeded);
	}

	/**
	 * @return value of ShortMessage
	 */
	public final java.lang.String getShortMessage()
	{
		return getShortMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ShortMessage
	 */
	public final java.lang.String getShortMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShortMessage.toString());
	}

	/**
	 * Set value of ShortMessage
	 * @param shortmessage
	 */
	public final void setShortMessage(java.lang.String shortmessage)
	{
		setShortMessage(getContext(), shortmessage);
	}

	/**
	 * Set value of ShortMessage
	 * @param context
	 * @param shortmessage
	 */
	public final void setShortMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shortmessage)
	{
		getMendixObject().setValue(context, MemberNames.ShortMessage.toString(), shortmessage);
	}

	/**
	 * @return value of LongMessage
	 */
	public final java.lang.String getLongMessage()
	{
		return getLongMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of LongMessage
	 */
	public final java.lang.String getLongMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LongMessage.toString());
	}

	/**
	 * Set value of LongMessage
	 * @param longmessage
	 */
	public final void setLongMessage(java.lang.String longmessage)
	{
		setLongMessage(getContext(), longmessage);
	}

	/**
	 * Set value of LongMessage
	 * @param context
	 * @param longmessage
	 */
	public final void setLongMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longmessage)
	{
		getMendixObject().setValue(context, MemberNames.LongMessage.toString(), longmessage);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return docmosisResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmosiscloud.proxies.DocmosisResponse that = (docmosiscloud.proxies.DocmosisResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
