// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloud.proxies;

public enum Enum_RenderRequest_StoreTo
{
	stream(new java.lang.String[][] { new java.lang.String[] { "en_US", "stream" }, new java.lang.String[] { "nl_NL", "stream" }, new java.lang.String[] { "de_DE", "stream" }, new java.lang.String[] { "fr_FR", "stream" } }),
	mailto(new java.lang.String[][] { new java.lang.String[] { "en_US", "mailto" }, new java.lang.String[] { "nl_NL", "mailto" }, new java.lang.String[] { "de_DE", "mailto" }, new java.lang.String[] { "fr_FR", "mailto" } }),
	storage(new java.lang.String[][] { new java.lang.String[] { "en_US", "storage" }, new java.lang.String[] { "nl_NL", "storage" }, new java.lang.String[] { "de_DE", "storage" }, new java.lang.String[] { "fr_FR", "storage" } }),
	s3(new java.lang.String[][] { new java.lang.String[] { "en_US", "s3" }, new java.lang.String[] { "nl_NL", "s3" }, new java.lang.String[] { "de_DE", "s3" }, new java.lang.String[] { "fr_FR", "s3" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_RenderRequest_StoreTo(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
