// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloud.proxies;

public class Request
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocmosisCloud.Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		APIAccessKey("APIAccessKey"),
		APIEndPoint("APIEndPoint"),
		RequestID("RequestID");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject)
	{
		if (requestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, requestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestMendixObject = requestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Request.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmosiscloud.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmosiscloud.proxies.Request.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static docmosiscloud.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DocmosisCloud.GetSampleDataRequest", mendixObject.getType())) {
			return docmosiscloud.proxies.GetSampleDataRequest.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DocmosisCloud.RenderRequest", mendixObject.getType())) {
			return docmosiscloud.proxies.RenderRequest.initialize(context, mendixObject);
		}
		return new docmosiscloud.proxies.Request(context, mendixObject);
	}

	public static docmosiscloud.proxies.Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmosiscloud.proxies.Request.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of APIAccessKey
	 */
	public final java.lang.String getAPIAccessKey()
	{
		return getAPIAccessKey(getContext());
	}

	/**
	 * @param context
	 * @return value of APIAccessKey
	 */
	public final java.lang.String getAPIAccessKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.APIAccessKey.toString());
	}

	/**
	 * Set value of APIAccessKey
	 * @param apiaccesskey
	 */
	public final void setAPIAccessKey(java.lang.String apiaccesskey)
	{
		setAPIAccessKey(getContext(), apiaccesskey);
	}

	/**
	 * Set value of APIAccessKey
	 * @param context
	 * @param apiaccesskey
	 */
	public final void setAPIAccessKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apiaccesskey)
	{
		getMendixObject().setValue(context, MemberNames.APIAccessKey.toString(), apiaccesskey);
	}

	/**
	 * @return value of APIEndPoint
	 */
	public final java.lang.String getAPIEndPoint()
	{
		return getAPIEndPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of APIEndPoint
	 */
	public final java.lang.String getAPIEndPoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.APIEndPoint.toString());
	}

	/**
	 * Set value of APIEndPoint
	 * @param apiendpoint
	 */
	public final void setAPIEndPoint(java.lang.String apiendpoint)
	{
		setAPIEndPoint(getContext(), apiendpoint);
	}

	/**
	 * Set value of APIEndPoint
	 * @param context
	 * @param apiendpoint
	 */
	public final void setAPIEndPoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String apiendpoint)
	{
		getMendixObject().setValue(context, MemberNames.APIEndPoint.toString(), apiendpoint);
	}

	/**
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID()
	{
		return getRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestID.toString());
	}

	/**
	 * Set value of RequestID
	 * @param requestid
	 */
	public final void setRequestID(java.lang.String requestid)
	{
		setRequestID(getContext(), requestid);
	}

	/**
	 * Set value of RequestID
	 * @param context
	 * @param requestid
	 */
	public final void setRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestID.toString(), requestid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmosiscloud.proxies.Request that = (docmosiscloud.proxies.Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
