// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloud.proxies;

public class Response
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DocmosisCloud.Response";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Result("Result"),
		ShortMessage("ShortMessage"),
		LongMessage("LongMessage"),
		RequestID("RequestID"),
		Response_Exception("DocmosisCloud.Response_Exception"),
		Response_Http("DocmosisCloud.Response_Http");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Response(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DocmosisCloud.Response"));
	}

	protected Response(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject responseMendixObject)
	{
		if (responseMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("DocmosisCloud.Response", responseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DocmosisCloud.Response");

		this.responseMendixObject = responseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Response.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static docmosiscloud.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return docmosiscloud.proxies.Response.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static docmosiscloud.proxies.Response initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DocmosisCloud.GetSampleDataResponse", mendixObject.getType()))
			return docmosiscloud.proxies.GetSampleDataResponse.initialize(context, mendixObject);

		if (com.mendix.core.Core.isSubClassOf("DocmosisCloud.RenderResponse", mendixObject.getType()))
			return docmosiscloud.proxies.RenderResponse.initialize(context, mendixObject);

		return new docmosiscloud.proxies.Response(context, mendixObject);
	}

	public static docmosiscloud.proxies.Response load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return docmosiscloud.proxies.Response.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of Result
	 * @param result
	 */
	public final docmosiscloud.proxies.Enum_Response_Result getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final docmosiscloud.proxies.Enum_Response_Result getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Result.toString());
		if (obj == null)
			return null;

		return docmosiscloud.proxies.Enum_Response_Result.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(docmosiscloud.proxies.Enum_Response_Result result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, docmosiscloud.proxies.Enum_Response_Result result)
	{
		if (result != null)
			getMendixObject().setValue(context, MemberNames.Result.toString(), result.toString());
		else
			getMendixObject().setValue(context, MemberNames.Result.toString(), null);
	}

	/**
	 * @return value of ShortMessage
	 */
	public final java.lang.String getShortMessage()
	{
		return getShortMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ShortMessage
	 */
	public final java.lang.String getShortMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ShortMessage.toString());
	}

	/**
	 * Set value of ShortMessage
	 * @param shortmessage
	 */
	public final void setShortMessage(java.lang.String shortmessage)
	{
		setShortMessage(getContext(), shortmessage);
	}

	/**
	 * Set value of ShortMessage
	 * @param context
	 * @param shortmessage
	 */
	public final void setShortMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String shortmessage)
	{
		getMendixObject().setValue(context, MemberNames.ShortMessage.toString(), shortmessage);
	}

	/**
	 * @return value of LongMessage
	 */
	public final java.lang.String getLongMessage()
	{
		return getLongMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of LongMessage
	 */
	public final java.lang.String getLongMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LongMessage.toString());
	}

	/**
	 * Set value of LongMessage
	 * @param longmessage
	 */
	public final void setLongMessage(java.lang.String longmessage)
	{
		setLongMessage(getContext(), longmessage);
	}

	/**
	 * Set value of LongMessage
	 * @param context
	 * @param longmessage
	 */
	public final void setLongMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longmessage)
	{
		getMendixObject().setValue(context, MemberNames.LongMessage.toString(), longmessage);
	}

	/**
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID()
	{
		return getRequestID(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestID
	 */
	public final java.lang.String getRequestID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestID.toString());
	}

	/**
	 * Set value of RequestID
	 * @param requestid
	 */
	public final void setRequestID(java.lang.String requestid)
	{
		setRequestID(getContext(), requestid);
	}

	/**
	 * Set value of RequestID
	 * @param context
	 * @param requestid
	 */
	public final void setRequestID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestid)
	{
		getMendixObject().setValue(context, MemberNames.RequestID.toString(), requestid);
	}

	/**
	 * @return value of Response_Exception
	 */
	public final docmosiscloud.proxies.Exception getResponse_Exception() throws com.mendix.core.CoreException
	{
		return getResponse_Exception(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_Exception
	 */
	public final docmosiscloud.proxies.Exception getResponse_Exception(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		docmosiscloud.proxies.Exception result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Response_Exception.toString());
		if (identifier != null)
			result = docmosiscloud.proxies.Exception.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Response_Exception
	 * @param response_exception
	 */
	public final void setResponse_Exception(docmosiscloud.proxies.Exception response_exception)
	{
		setResponse_Exception(getContext(), response_exception);
	}

	/**
	 * Set value of Response_Exception
	 * @param context
	 * @param response_exception
	 */
	public final void setResponse_Exception(com.mendix.systemwideinterfaces.core.IContext context, docmosiscloud.proxies.Exception response_exception)
	{
		if (response_exception == null)
			getMendixObject().setValue(context, MemberNames.Response_Exception.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Response_Exception.toString(), response_exception.getMendixObject().getId());
	}

	/**
	 * @return value of Response_Http
	 */
	public final docmosiscloud.proxies.Http getResponse_Http() throws com.mendix.core.CoreException
	{
		return getResponse_Http(getContext());
	}

	/**
	 * @param context
	 * @return value of Response_Http
	 */
	public final docmosiscloud.proxies.Http getResponse_Http(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		docmosiscloud.proxies.Http result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Response_Http.toString());
		if (identifier != null)
			result = docmosiscloud.proxies.Http.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Response_Http
	 * @param response_http
	 */
	public final void setResponse_Http(docmosiscloud.proxies.Http response_http)
	{
		setResponse_Http(getContext(), response_http);
	}

	/**
	 * Set value of Response_Http
	 * @param context
	 * @param response_http
	 */
	public final void setResponse_Http(com.mendix.systemwideinterfaces.core.IContext context, docmosiscloud.proxies.Http response_http)
	{
		if (response_http == null)
			getMendixObject().setValue(context, MemberNames.Response_Http.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Response_Http.toString(), response_http.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return responseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final docmosiscloud.proxies.Response that = (docmosiscloud.proxies.Response) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DocmosisCloud.Response";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
