// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package docmosiscloud.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the DocmosisCloud module
	public static java.lang.String contentType_ApplicationJSON(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("DocmosisCloud.ContentType_ApplicationJSON").withParams(params).execute(context);
	}
	public static java.lang.String contentType_ApplicationUrlEncoded(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("DocmosisCloud.ContentType_ApplicationUrlEncoded").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.Enum_Response_Result convert_SuccessToEnumeration(IContext context, boolean _success)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Success", _success);
		java.lang.String result = (java.lang.String) Core.microflowCall("DocmosisCloud.Convert_SuccessToEnumeration").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.Enum_Response_Result.valueOf(result);
	}
	public static docmosiscloud.proxies.GetSampleDataResponse cWS_GetSampleData(IContext context, docmosiscloud.proxies.GetSampleDataRequest _getSampleDataRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GetSampleDataRequest", _getSampleDataRequest == null ? null : _getSampleDataRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.CWS_GetSampleData").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.GetSampleDataResponse.initialize(context, result);
	}
	public static docmosiscloud.proxies.RenderResponse cWS_Render(IContext context, java.lang.String _jSONData, docmosiscloud.proxies.RenderRequest _renderRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JSONData", _jSONData);
		params.put("RenderRequest", _renderRequest == null ? null : _renderRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.CWS_Render").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.RenderResponse.initialize(context, result);
	}
	public static void fileDocument_Base64Decode(IContext context, java.lang.String _base64String, system.proxies.FileDocument _fileDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Base64String", _base64String);
		params.put("FileDocument", _fileDocument == null ? null : _fileDocument.getMendixObject());
		Core.microflowCall("DocmosisCloud.FileDocument_Base64Decode").withParams(params).execute(context);
	}
	public static java.lang.String generateUUID(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.String) Core.microflowCall("DocmosisCloud.GenerateUUID").withParams(params).execute(context);
	}
	public static java.lang.String getSampleDataRequest_CreateRequestURL(IContext context, docmosiscloud.proxies.GetSampleDataRequest _getSampleDataRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GetSampleDataRequest", _getSampleDataRequest == null ? null : _getSampleDataRequest.getMendixObject());
		return (java.lang.String) Core.microflowCall("DocmosisCloud.GetSampleDataRequest_CreateRequestURL").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.GetSampleDataRequest getSampleDataRequest_Initialize(IContext context, java.lang.String _templateName, java.lang.String _aPIAccessKey, java.lang.String _aPIEndPoint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateName", _templateName);
		params.put("APIAccessKey", _aPIAccessKey);
		params.put("APIEndPoint", _aPIEndPoint);
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.GetSampleDataRequest_Initialize").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.GetSampleDataRequest.initialize(context, result);
	}
	public static docmosiscloud.proxies.GetSampleDataResponse getSampleDataRequest_Validate(IContext context, docmosiscloud.proxies.GetSampleDataRequest _getSampleDataRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GetSampleDataRequest", _getSampleDataRequest == null ? null : _getSampleDataRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.GetSampleDataRequest_Validate").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.GetSampleDataResponse.initialize(context, result);
	}
	public static java.lang.String renderRequest_ExportJSONWithData(IContext context, java.lang.String _jSONData, docmosiscloud.proxies.RenderRequest _renderRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JSONData", _jSONData);
		params.put("RenderRequest", _renderRequest == null ? null : _renderRequest.getMendixObject());
		return (java.lang.String) Core.microflowCall("DocmosisCloud.RenderRequest_ExportJSONWithData").withParams(params).execute(context);
	}
	public static docmosiscloud.proxies.RenderRequest renderRequest_Initialize(IContext context, java.lang.String _templateName, java.lang.String _outputName, java.lang.String _aPIAccessKey, java.lang.String _aPIEndPoint)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateName", _templateName);
		params.put("OutputName", _outputName);
		params.put("APIAccessKey", _aPIAccessKey);
		params.put("APIEndPoint", _aPIEndPoint);
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.RenderRequest_Initialize").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.RenderRequest.initialize(context, result);
	}
	public static docmosiscloud.proxies.RenderResponse renderRequest_Validate(IContext context, docmosiscloud.proxies.RenderRequest _renderRequest)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RenderRequest", _renderRequest == null ? null : _renderRequest.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("DocmosisCloud.RenderRequest_Validate").withParams(params).execute(context);
		return result == null ? null : docmosiscloud.proxies.RenderResponse.initialize(context, result);
	}
	public static void request_UpdateAPI(IContext context, java.lang.String _aPIAccessKey, java.lang.String _aPIEndPoint, docmosiscloud.proxies.Request _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("APIAccessKey", _aPIAccessKey);
		params.put("APIEndPoint", _aPIEndPoint);
		params.put("Request", _request == null ? null : _request.getMendixObject());
		Core.microflowCall("DocmosisCloud.Request_UpdateAPI").withParams(params).execute(context);
	}
	public static void request_Validate(IContext context, docmosiscloud.proxies.Request _request, java.lang.String _processName, docmosiscloud.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Request", _request == null ? null : _request.getMendixObject());
		params.put("ProcessName", _processName);
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("DocmosisCloud.Request_Validate").withParams(params).execute(context);
	}
	public static java.lang.String requestURL_Create(IContext context, java.lang.String _aPIEndPoint, java.lang.String _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("APIEndPoint", _aPIEndPoint);
		params.put("Request", _request);
		return (java.lang.String) Core.microflowCall("DocmosisCloud.RequestURL_Create").withParams(params).execute(context);
	}
	public static java.lang.String requestURL_Sanitize(IContext context, java.lang.String _requestURL)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RequestURL", _requestURL);
		return (java.lang.String) Core.microflowCall("DocmosisCloud.RequestURL_Sanitize").withParams(params).execute(context);
	}
	public static void response_Enrich(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _requestURL, java.lang.String _requestID, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("RequestURL", _requestURL);
		params.put("RequestID", _requestID);
		params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		Core.microflowCall("DocmosisCloud.Response_Enrich").withParams(params).execute(context);
	}
	public static void response_EnrichException(IContext context, docmosiscloud.proxies.Response _response, java.lang.String _requestURL, java.lang.String _requestID, system.proxies.HttpResponse _httpResponse, system.proxies.Error _error)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("RequestURL", _requestURL);
		params.put("RequestID", _requestID);
		params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("Error", _error == null ? null : _error.getMendixObject());
		Core.microflowCall("DocmosisCloud.Response_EnrichException").withParams(params).execute(context);
	}
	public static void response_SetValidationMessage(IContext context, java.lang.String _processName, docmosiscloud.proxies.Response _response, java.lang.String _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ProcessName", _processName);
		params.put("Response", _response == null ? null : _response.getMendixObject());
		params.put("Message", _message);
		Core.microflowCall("DocmosisCloud.Response_SetValidationMessage").withParams(params).execute(context);
	}
	public static void response_WrapUpValidationFeedback(IContext context, docmosiscloud.proxies.Response _response)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Response", _response == null ? null : _response.getMendixObject());
		Core.microflowCall("DocmosisCloud.Response_WrapUpValidationFeedback").withParams(params).execute(context);
	}
	public static void urlEncodedRequest_Add(IContext context, java.util.List<docmosiscloud.proxies.KeyValue> _keyValueList, java.lang.String _key, java.lang.String _value)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_keyValueList = null;
		if (_keyValueList != null)
		{
			listparam_keyValueList = new java.util.ArrayList<>();
			for (docmosiscloud.proxies.KeyValue obj : _keyValueList)
				listparam_keyValueList.add(obj.getMendixObject());
		}
		params.put("KeyValueList", listparam_keyValueList);

		params.put("Key", _key);
		params.put("Value", _value);
		Core.microflowCall("DocmosisCloud.UrlEncodedRequest_Add").withParams(params).execute(context);
	}
	public static java.lang.String urlEncodedRequest_CreateRequestURL(IContext context, java.util.List<docmosiscloud.proxies.KeyValue> _keyValueList, java.lang.String _requestURL)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.ArrayList<IMendixObject> listparam_keyValueList = null;
		if (_keyValueList != null)
		{
			listparam_keyValueList = new java.util.ArrayList<>();
			for (docmosiscloud.proxies.KeyValue obj : _keyValueList)
				listparam_keyValueList.add(obj.getMendixObject());
		}
		params.put("KeyValueList", listparam_keyValueList);

		params.put("RequestURL", _requestURL);
		return (java.lang.String) Core.microflowCall("DocmosisCloud.UrlEncodedRequest_CreateRequestURL").withParams(params).execute(context);
	}
	public static java.util.List<docmosiscloud.proxies.KeyValue> urlEncodedRequest_Initialize(IContext context, docmosiscloud.proxies.Request _request)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Request", _request == null ? null : _request.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("DocmosisCloud.UrlEncodedRequest_Initialize").withParams(params).execute(context);
		java.util.List<docmosiscloud.proxies.KeyValue> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(docmosiscloud.proxies.KeyValue.initialize(context, obj));
		}
		return result;
	}
}